reformatted function

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,14 +18,13 @@ install:
   - arduino --install-library log4Esp
 script:
   - buildExamples() {
-
-    local sketches=$(find $PWD/examples -name *.ino)
-    for sketch in $sketches; do
-      arduino --verbose-build --verify $sketch;
-      local result=$?
-      if [ $result -ne 0 ]; then
-        echo "Build failed ($1)"
-        return $result
-      fi
-    done
-  }
+      local sketches=$(find $PWD/examples -name *.ino)
+      for sketch in $sketches; do
+        arduino --verbose-build --verify $sketch;
+        local result=$?
+        if [ $result -ne 0 ]; then
+          echo "Build failed ($1)"
+          return $result
+        fi
+      done
+    }
