comment out arduino instruction

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,6 +20,12 @@ script:
   - buildExamples() {
       local sketches=$(find $PWD/examples -name *.ino)
       for sketch in $sketches; do
-
+        echo $sketch
+        #arduino --verbose-build --verify $sketch;
+        local result=$?
+        if [ $result -ne 0 ]; then
+          echo "Build failed ($1)"
+          return $result
+        fi
       done
     }
